# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43525c50eddd6d79b565e998ba6ac808496e2f34956b6035d0080137f719b5234f8c9f49352d1b684158b3be4437619f2a3356883fdf70359a5dd29e597390a2

test:
  secret_key_base: e0b820bfe138de9f64c4bbacc7bb22a632c59b82816f3d70e23c12db368df82d7d670dbaa1c134609a0f49ed55fa0e786b95adec0be5b2d2f27cba68c67ad117

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 253b97808797490975b2d4c8aeec34e4e8cac156a5b6c94c8c7d4669ad90ad789db7a9821ebe1d6d8450b1581e6a6eb2dbc66a77439e32063a46e09a44fe1f86
